/**
 * Generates per-icon entry files and updates package.json exports map.
 *
 * For each icon at src/icons/<category>/<name>.ts, produces:
 *   src/entries/<name>.ts  — side-effect module that self-registers the icon
 *
 * Then writes the exports field in package.json so consumers can do:
 *   import '@latty-ds/icons/xmark'
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'fs';
import { resolve, join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const ICONS_SRC = join(ROOT, 'src/icons');
const ENTRIES_DIR = join(ROOT, 'src/entries');

mkdirSync(ENTRIES_DIR, { recursive: true });

// kebab-case → camelCase + 'Svg'  (e.g. 'arrow-down' → 'arrowDownSvg')
function toExportName(name) {
  return name.replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + 'Svg';
}

// Collect all icons: { name, category, exportName }
const icons = [];

for (const entry of readdirSync(ICONS_SRC, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;
  const category = entry.name;
  for (const file of readdirSync(join(ICONS_SRC, category))) {
    if (!file.endsWith('.ts') || file === 'index.ts') continue;
    const name = file.replace(/\.ts$/, '');
    icons.push({ name, category, exportName: toExportName(name) });
  }
}

icons.sort((a, b) => a.name.localeCompare(b.name));

// Generate entry files
for (const { name, category, exportName } of icons) {
  const content =
    `// Auto-generated by scripts/build-entries.mjs — do not edit\n` +
    `import { iconRegistry } from '../registry/icon-registry';\n` +
    `import { ${exportName} } from '../icons/${category}/${name}';\n` +
    `iconRegistry.registerIcon('${name}', ${exportName});\n`;

  writeFileSync(join(ENTRIES_DIR, `${name}.ts`), content, 'utf8');
}

// Update package.json exports map
const pkgPath = join(ROOT, 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));

const perIconExports = Object.fromEntries(
  icons.map(({ name }) => [`./${name}`, { default: `./dist/entries/${name}.js` }])
);

pkg.exports = {
  '.': { types: './dist/index.d.ts', default: './dist/index.js' },
  ...perIconExports
};

// Only entry files and the main index have side effects
pkg.sideEffects = ['./dist/index.js', './dist/entries/*.js'];

writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');

const count = icons.length;
process.stdout.write(`Generated ${count} icon entry files → src/entries/\n`);
process.stdout.write(`Updated package.json exports (${count} icon paths + bare entry)\n`);
