import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Autogenerated from the docs/ folder structure instead of a hand-curated
// array — scales with zero maintenance as pages are added (the manual
// version required remembering to edit this file every time, which is
// exactly the kind of thing that gets forgotten). Category label/position
// comes from each folder's `_category_.json`; within a category, ordering
// follows `sidebar_position` frontmatter where set, alphabetical otherwise
// (which already matches the intended order for Components).
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }]
};

export default sidebars;
